version: '3.7'

services:
  pg-master:
    image: postgres
    container_name: pg-master
    environment:
      POSTGRES_PASSWORD: masterpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - pg-network
    volumes:
      - pg-master-data:/var/lib/postgresql/data
      - ./master-init.sh:/docker-entrypoint-initdb.d/master-init.sh
    ports:
      - "5432:5432"

  pg-slave:
    image: postgres
    container_name: pg-slave
    environment:
      POSTGRES_PASSWORD: slavepassword
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - pg-network
    volumes:
      - pg-slave-data:/var/lib/postgresql/data
      - ./slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh
    depends_on:
      - pg-master
    restart: unless-stopped  
    ports:
      - "5433:5432"

volumes:
  pg-master-data:
    driver: local
    driver_opts:
      type: none
      device: ./master-data
      o: bind
  pg-slave-data:
    driver: local
    driver_opts:
      type: none
      device: ./slave-data
      o: bind


networks:
  pg-network:
    driver: bridge

